# ESA-Web Global Configuration

# server configuration
server:
  service-name: esa-web
  port: 8080
  time-format: 2006-01-02 15:04:05.000

# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  prefix: '[ESA-SOURCE-ZKILL]'
  director: './log/'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

# mysql configuration
mysql:
  path: mysql:3306
#  path: 127.0.0.1:3306
  dbname: eve_situation_awareness
  username: root
  password: 123456
  config: charset=utf8&parseTime=True&loc=Local
  max-idle-conns: 10
  max-open-conns: 100

# redis configuration
redis:
  path:
