# ESA-Source-ZKill Global Configuration

# server configuration
server:
  service-name: eas-source-zkill
  port: 8090
  time-format: 2006-01-02 15:04:05.000

# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  prefix: '[EAS-SOURCE-ZKILL]'
  director: './log/'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

# mysql configuration
mysql:
  path:
  dbname:
  username: root
  password: 123
  config: charset=utf8&parseTime=True&loc=Local
  max-idle-conns: 10
  max-open-conns: 100

# kafka configuration
kafka:
#  path: 127.0.0.1:9092
  path: kafka-node1:9092,kafka-node2:9092,kafka-node3:9092
#  path: node1:33143,node2:33143,node3:33143
#  path: 192.168.13.107:9092,192.168.13.108:9092,192.168.13.109:9092
  username: zkillinfo
  password: 8103de119d72
  topic: zkill
  group: source

# redis configuration
redis:
  path:
