# ESA-Admin Global Configuration

# server configuration
server:
  port: 8090
  time-format: 2006-01-02 15:04:05.000

# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  prefix: '[EAS-ADMIN]'
  director: 'log'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

# mysql configuration
mysql:
  path:
  dbname:
  username:
  password:
  max-idle-conns: 10
  max-open-conns: 100