name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: test
      run: ls

    - name: Install dependencies
      run: ./eas-go-service/build.sh binary
      shell: bash

    - name: test
      run: ls
