name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: test
      run: chmod u+x ./eas-go-service/build.sh

    - name: Build
      run: sudo ./eas-go-service/build.sh binary
      shell: bash

    - name: test
      run: ls
