name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: cd eas-go-service
      run: cd eas-go-service
      
    - name: test
      run: ls
      
    - name: Install dependencies
      run: make -C eas-go-service
      
    - name: test
      run: ls
